name: C/C++ CI

on:
  push:
    branches: [master, auto_testing, waves_tests]
  pull_request:
    branches: [master, auto_testing]

jobs:
  tests-native:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq g++-8 cmake build-essential python3-pip python3-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
    - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    - name: run-tests
      run: make 
      working-directory: tests

      #test-coverage:
      #  name: Measure test coverage
      #  runs-on: ubuntu-18.04
      #  steps:
      #    # working-directory: tests
      #    - uses: actions/checkout@v2
      #      with:
      #        submodules: 'recursive'
      #    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      #    - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      #    - run: sudo apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
      #    - run: sudo apt-get update -qq
      #    - run: sudo apt-get install -qq g++-8
      #    - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      #    - run: sudo apt-get install cmake build-essential python3-virtualenv python3-pip nodejs tar gzip libclang-7-dev llvm llvm-dev libllvm7 llvm-7 llvm-7-dev clang-7 libstdc++-7-dev # might have to happen after we update g++
      #    - run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 90
      #    - run: sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-7 90
      #    - run: sudo update-alternatives --install /usr/bin/llvm-profdata llvm-profdata /usr/bin/llvm-profdata-7 90
      #    - run: sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-7 90
      #    # - run: git fetch origin master:refs/remotes/origin/master
      #    #- run: make install-test-dependencies
      #    #- run: export CXX=clang++-7 && make install-coverage-dependencies
      #    #- run: export CXX=clang++-7 && make coverage
      #    #- run: curl -s https://codecov.io/bash | bash
